#!/usr/bin/env zsh

fpath=("$DOTFILES/zsh/plugins" $fpath)


###############################################################################
# Navigation
###############################################################################

setopt AUTO_CD

setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

setopt CORRECT
setopt CDABLE_VARS
setopt EXTENDED_GLOB


###############################################################################
# Navigation
###############################################################################

setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY


###############################################################################
# Colors
###############################################################################

eval "$(dircolors -b "$ZDOTDIR/dircolors")"


###############################################################################
# Aliases
###############################################################################

source "$DOTFILES/aliases/aliases.sh"


###############################################################################
# fzf
###############################################################################

if command -v fzf >/dev/null; then
    source "$DOTFILES/zsh/fzf.zsh"
fi


###############################################################################
# Bindings
###############################################################################

source "$DOTFILES/zsh/bindings.zsh"


source "$DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

if command -v starship >/dev/null; then
    export STARSHIP_CONFIG="$DOTFILES/starship/config.toml"
    eval "$(starship init zsh)"
fi

if command -v direnv >/dev/null; then
    eval "$(direnv hook zsh)"
fi

if [ -f "$HOME/.asdf/asdf.sh" ]; then
    . "$HOME/.asdf/asdf.sh"
    fpath=("$ASDF_DIR/completions" $fpath)
fi


###############################################################################
# Completion
###############################################################################

source $DOTFILES/zsh/completion.zsh
