#!/usr/bin/env bash
set -Eeuo pipefail

if grep -qi microsoft /proc/version >/dev/null; then
    exec /mnt/c/Windows/System32/paste.exe
elif type xclip >/dev/null 2>&1; then
    exec xclip -selection clipboard -out
elif type xsel >/dev/null 2>&1; then
    exec xsel --output --clipboard
else
    >&2 echo "Unable determine pasteboard server"
    exit 1
fi
